#!/usr/bin/perl

use warnings;
use strict;

if (@ARGV != 1) {
	print <<EOF
Usage: $0 <address>
EOF
	; # This is needed to avoid compilation errors...for some reason.
	exit 1;
}
my $line = $ARGV[0];
$line = `./ipv6-long $line`;
chomp $line;
die "\n" unless $line =~ s/://g;
$line = join('.', split(//, reverse $line));
print "$line.ip6.arpa\n";
